"""empty message

Revision ID: 406d17de3e33
Revises: b09831187638
Create Date: 2021-01-14 15:21:10.411932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '406d17de3e33'
down_revision = 'b09831187638'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('language', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'language')
    # ### end Alembic commands ###
